config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :articles, except: [:index] do
    collection do
      get 'ranking'
      get 'search'
      get 'favorites'
    end
  end

  resources :tags
  get 'fetch', to: 'articles#fetch'
  get 'admin', to: 'articles#manage'
  get 'feed', to: 'articles#feed', format: 'rss'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :views

  acts_as_taggable

  scope :related, ->(category_id, article_id) {
    where(category_id: category_id)
    .where.not(id: article_id)
    .limit(12)
  }
  scope :popular, ->(limit) {
    joins(:views)
    .order('count(views.id) desc')
    .group('articles.id')
    .limit(limit)
  }
  scope :in_day, -> { where('views.created_at BETWEEN ? AND ?', Time.zone.now.beginning_of_day, Time.zone.now.end_of_day) }
  scope :latest, -> { order(created_at: :DESC) }
  scope :published, -> { where(published: true) }
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :basic_auth
  before_action :set_footer_tags

  def basic_auth
    authenticate_or_request_with_http_basic do |user, pass|
      user == "admin" && "eropit333admin"
    end
  end

  def set_footer_tags
    @footer_tags = ActsAsTaggableOn::Tag.most_used(6)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :basic_auth, only: [:show, :ranking, :search, :favorites, :feed]
  before_action :set_sidebar_tags, only: [:show, :ranking, :search, :favorites]

  require 'fetch_video'

  def show
    @article = Article.find_by(id: params[:id])
    @related_articles = Article.related(@article.category_id, @article.id).published.limit(6)
    @recommendations = Article.tagged_with(ActsAsTaggableOn::Tag.most_used, :any => true).published.take(4)
    @title = @article.title
    create_view(@article.id)
  end

  def ranking
    @articles = Article.in_day.popular(20).published
    @title = '人気動画'
  end

  def search
    @articles = Article.tagged_with(params[:search]).published.page(params[:page])
    @title = "『#{ params[:search] }』の動画"
  end

  def favorites
    if params[:ids].present?
      ids = params[:ids].to_s.split(',')
      @favorite_articles = Article.where(id: ids).published.page(params[:page])
    else
      @favorite_articles = Article.where(id: 0).page(params[:page])
    end
    @title = 'お気に入り動画'
  end

  def new
    @category = Category.new
    @article = Article.new

    gon.available_tags = Article.tags_on(:tags).pluck(:name)
  end

  def create
    article = Article.new article_params

    if article.save
      redirect_to article
    else
      render 'new'
    end
  end

  def edit
    @category = Category.new
    @article = Article.find_by(id: params[:id])

    gon.article_tags = @article.tag_list
    gon.available_tags = Article.tags_on(:tags).pluck(:name)
  end

  def update
    article = Article.find_by(id: params[:id])
    article.update_attributes article_params

    if article.save
      redirect_to article
    else
      render 'edit'
    end
  end

  def destroy
    article = Article.find_by(id: params[:id])
    if article.destroy
      redirect_to admin_path
    else
      redirect_to admin_path
    end
  end

  def manage
    @category = Category.new
    @articles = Article.all.page(params[:page])
    @title = 'Admin'
  end

  def feed
    @articles = Article.latest.published.limit(20)
    respond_to do |format|
      format.rss
    end
  end

  def fetch
    f = FetchVideo.new
    f.nukistream
    f.masutabe
    f.javym
    redirect_to admin_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :description, :thumbnail, :link, :category_id, :duration, :host, :published, :tag_list)
    end

    def create_view(article_id)
      v = View.new
      v.article_id = article_id
      v.save!
    end

    def set_sidebar_tags
      @sidebar_tags = ActsAsTaggableOn::Tag.most_used(30)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :basic_auth, only: [:show]

  def create
    category = Category.new category_params
    redirect_to admin_path if category.save
  end

  def show
    #code
  end

  private
    def category_params
      params.require(:category).permit(:title)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :basic_auth, only: [:index]

  def index
    @latest_articles = Article.latest.published.page(params[:page])
    @popular_articles = Article.in_day.popular(6).published
    @recommendations = Article.tagged_with(ActsAsTaggableOn::Tag.most_used, :any => true).published.take(4)
    @sidebar_tags = ActsAsTaggableOn::Tag.most_used(30)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @title = 'タグ管理'
    @tags = ActsAsTaggableOn::Tag.all.page(params[:page])
  end

  def edit
    @title = 'タグ編集'
    @tag = ActsAsTaggableOn::Tag.find_by(id: params[:id])
  end

  def update
    tag = ActsAsTaggableOn::Tag.find_by(id: params[:id])
    tag.update_attributes tag_params

    redirect_to tags_path
  end

  private
    def tag_params
      params.require(:tag).permit(:name, :mean, :suf_words, :pre_words)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/edit.html.erb
<div class="row">
  <div class="left three cols">
    <%= render 'layouts/manage_side_bar' %>
  </div>
  <div class="right nine cols article-form">
    <div class="card">
      <div class="head tx-center" style="border-bottom: #eee 1px solid">
        記事編集画面
      </div>
      <% unless @article.nil? %>
        <% if @article.errors.any? %>
          <% @article.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger" role="alert"><%= msg %></div>
          <% end %>
        <% end %>
      <% end %>
      <div class="qwertize">
        <%= form_for @article do |f| %>
  
          <div class="row">
            <div class="ten cols">
              <span style="font-weight: 600">渋谷系ギャルをクラブで捕まえてホテルで4P！予想通りSEX大好き痴女でしたｗ</span>
            </div>           
            <div class="two cols tx-right">
              <%= f.check_box :published, class:'' %>
              <label for="article_published">公開中</label>
            </div>
          </div>
          
          <div class="row">
            <div class="four cols">
              <img src="" class="image-insert"></img>
            </div>
            <div class="eight cols">
              <label>Thumbnail URL</label>
              <%= f.text_field :thumbnail %>
              <label>Link URL</label>
              <%= f.text_field :link %>
              <div class="row lower-input">
                <div class="four cols">
                  <label>Duration</label>
                  <%= f.text_field :duration %>
                </div>
                <div class="four cols">
                  <label>Host</label>
                  <%= f.text_field :host %>
                </div>
                <div class="four cols">
                  <label>Category</label>
                  <%= f.collection_select :category_id, Category.all, :id, :title %>
                </div>
              </div>
            </div>
          </div>
                    
          <div class="row">
            <div class="twelve cols">
              <label>Title</label>
              <%= f.text_field :title %>
            </div>
          </div>          
                    
          <div class="row">
            <div class="twelve cols">
              <label>Description</label>
              <%= f.text_area :description %>
            </div>
            
            <label>Tags</label>
            <ul id="article-tags"></ul>
          </div>

          </div>
        <div class="foot">
          <a href="#" class="full-x card-btn">
              <%= f.submit '変更を保存', class: "btn fill-red" %>
          </a>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<style media="screen">
  .article-form input {
    width: 100%;
  }
  .image-insert {
    width: 100%;
    height: 222px;
  }
  #article_description {
    min-height: 160px;
  }
  .lower-input input {
    height: 36px;
  }
</style>

app/views/articles/favorites.html.erb
<div class="row">
  <div class="left three cols">
    <%= render 'layouts/sidebar' %>
  </div>
  <div class="right nine cols">
    <div class="feature-videos">
      <div class="row">
        <h6 class="favorite-heading"><i class="icon ion-star"></i>&nbsp;お気に入り動画</h6>
        <% if @favorite_articles.size > 0 %>
          <a class="remove-favorites"><i class="icon ion-trash-a"></i>&nbsp;お気に入りをすべて削除</a>
        <% else %>
          <p class="tx-center"><i class="icon icon ion-star"></i>&nbsp;お気に入り動画がありません</p>
        <% end %>
      </div>
      <% @favorite_articles.each_slice(2) do |articles| %>
        <div class="row">
          <% articles.each do |article| %>
            <div class="six cols card">
              <%= render 'layouts/article_card', article: article %>
            </div>
          <% end %>
        </div>
      <% end %>
      <div class="row tx-center">
        <%= paginate @favorite_articles %>
      </div>
    </div>
  </div>
</div>

app/views/articles/manage.html.erb
<div class="row">
  <div class="left three cols">
    <%= render 'layouts/manage_side_bar' %>
  </div>
  <div class="right nine cols">
    <% @articles.each_slice(1) do |articles| %>
      <div class="row admin-cards">
        <% articles.each do |article| %>
          <div class="twelve cols card">
              <div class="head">
                <%= link_to article_path(id: article.id), target: '_blank' do %>
                  <i class="icon ion-ios-film"></i>&nbsp;<%= article.title %>&nbsp;<i class="icon ion-share"></i>
                <% end %>
                <span class="published-switch">
                  <div class="qwertize">
                    <div class="switch" style="width: 160px; margin-top: 4px; margin-left: -140px;">
                      <input type="radio" name="lang-switch" id="lang-switch_1" value="1" checked="checked">
                      <label for="lang-switch_1" data-label="下書き">下書き</label>
                      <input type="radio" name="lang-switch" id="lang-switch_0" value="0">
                      <label for="lang-switch_0" data-label="公開">公開</label>
                    </div>
                  </div>
                </span>
              </div>
            <div class="body summary">
              <%= link_to article_path(id: article.id), target: '_blank' do %>
                <img src="<%= article.thumbnail %>" alt="<%= article.title %>" />
              <% end %>
              <div class="info video-summary">
                <p style="margin-bottom: -6px;"><%= article.description %></p>
                <div class="host">
                  <i class="icon ion-earth"></i>&nbsp;<%= article.host %>
                </div>
                <div class="admin-tags" style="width: 464px">
                  <% article.tag_list.each do |tag| %>
                    <%= render 'layouts/tag', tag: tag %>
                  <% end %>
                </div>
              </div>
            </div>
            <%= link_to edit_article_path(id: article.id) do %>
              <span class="edit-btn"><i class="icon ion-edit"></i>&nbsp;Edit</span>
            <% end %>
            <%= link_to article_path(id: article.id), method: :delete do %>
              <span class="delete-btn"><i class="icon ion-trash-a"></i>&nbsp;Delete</span>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="row tx-center">
      <%= paginate @articles %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="row">
  <div class="left three cols">
    <%= render 'layouts/manage_side_bar' %>
  </div>
  <div class="right nine cols article-form">
    <div class="card">
      <% unless @article.nil? %>
        <% if @article.errors.any? %>
          <% @article.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger" role="alert"><%= msg %></div>
          <% end %>
        <% end %>
      <% end %>
      <%= form_for @article do |f| %>
        <%= f.text_field :title, placeholder: 'Title', required: true %>
        <%= f.text_field :thumbnail, placeholder: 'Thumbnail', required: true %>
        <%= f.text_area :description, placeholder: 'Description', required: true %>
        <%= f.text_field :link, placeholder: 'Link', required: true %>
        <%= f.text_field :duration, placeholder: 'Duration', required: true %>
        <%= f.text_field :host, placeholder: 'Host', required: true %>
        <label>Category</label>
        <%= f.collection_select :category_id, Category.all, :id, :title, required: true %>
        <label>Tags</label>
        <ul id="article-tags"></ul>
        <%= f.submit 'Save', class: "btn fill-red" %>
      <% end %>
    </div>
  </div>
</div>

<style media="screen">
  .article-form input {
    width: 100%;
  }
</style>

app/views/articles/ranking.html.erb
<div class="row">
  <h6 class="sub-heading"><i class="icon ion-ribbon-b"></i>&nbsp;人気動画</h6>
</div>
<div class="twelve cols">
  <% @articles.each_slice(3) do |articles| %>
    <div class="row">
      <% articles.each do |article| %>
        <div class="four cols card">
          <%= render 'layouts/article_card', article: article %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/articles/search.html.erb
<div class="row">
  <h6 class="sub-heading">『<%= params[:search] %>』の動画</h6>
</div>
<div class="twelve cols">
  <% @articles.each_slice(3) do |articles| %>
    <div class="row">
      <% articles.each do |article| %>
        <div class="four cols card">
          <%= render 'layouts/article_card', article: article %>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="row tx-center">
    <%= paginate @articles %>
  </div>
  <div class="row">
    <h6 class="sub-heading">おすすめのタグ</h6>
  </div>
  <div class="twelve cols">
    <% @sidebar_tags.each do |tag| %>
      <%= render 'layouts/tag', tag: tag %>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<% urls = ['http://www.mgstage.com/js/mgs_sample_movie.js?p=200GANA-1077&s=1&c=6PYILNLH26JYZYLKBFKJYBLD3M',
           'http://www.mgstage.com/js/mgs_sample_movie.js?p=SIRO-2790&s=1&c=6PYILNLH26JYZYLKBFKJYBLD3M',
           'http://www.mgstage.com/js/mgs_sample_movie.js?p=200GANA-1040&s=1&c=6PYILNLH26JYZYLKBFKJYBLD3M',
           'http://www.mgstage.com/js/mgs_sample_movie.js?p=230ORE-095&s=1&c=6PYILNLH26JYZYLKBFKJYBLD3M',
           'http://www.mgstage.com/js/mgs_sample_movie.js?p=277DCV-001&s=1&c=6PYILNLH26JYZYLKBFKJYBLD3M'] %>
<div class="row">
  <%= render 'layouts/featured_videos' %>
</div>

<div class="tx-center">

  <%= render 'layouts/ad' %>
  <%= render 'layouts/ad-mobile' %>

</div>

<div class="row">
  <div class="right eight cols">
    <div class="row">
      <div class="twele cols card">
        <div class="head">
          <%= link_to @article.link, target: "_blank" do %>
            <%= @article.title %>
          <% end %>
        </div>
        <div class="body">
          <%= link_to @article.link, target: "_blank" do %>
            <img src="<%= @article.thumbnail %>" width="100%" alt="<%= @article.title %>" />
          <% end %>
          <div class="video-info">
            <div class="row" style="position: relative;">
              <div class="ten cols">
                <%= link_to @article.link, target: "_blank" do %>
                  <h1 class="video-title"><%= @article.title %></h1>
                <% end %>
              </div>
              <div class="two cols">
                <span data-video-id="<%= @article.id %>" class="add-favorite-btn"><i class="icon ion-plus"></i>&nbsp;お気に入りに追加</span>
              </div>
            </div>
            <div class="video-meta">
              <span class="left video-duration"><i class="icon ion-clock"></i>&nbsp;再生時間：<%= @article.duration %></span>
              <span class="right video-host"><i class="icon ion-earth"></i>&nbsp;<%= @article.host %></span>
            </div>
            <hr>
            <p><%= @article.description %></p>
            <%= link_to @article.link, target: "_blank" do %>
            <div class="tx-center">
              <span style="margin: 12px 0; width: 100%; padding: 8px;" class="btn btn-md fill-dark"><i class="icon ion-share"></i>&nbsp;動画を見る</span>
            </div>
            <% end %>
            <div class="tags">
              <% @article.tag_list.each do |tag| %>
                <%= render 'layouts/tag', tag: tag %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="left four cols">
    <div class="row">
      <h6 class="sub-heading">オススメMGS動画</h6>
    </div>
    <div class="tx-center">
      <script type="text/javascript" charset="utf-8" src="<%= urls[rand(urls.count)] %>"></script>
    </div>
    <%= render 'layouts/sidebar' %>
  </div>
  <div class="twelve cols">
    <div class="row">
      <h6 class="sub-heading">関連動画</h6>
    </div>
    <% @related_articles.each_slice(3) do |articles| %>
      <div class="row">
        <% articles.each do |article| %>
          <div class="four cols card">
            <%= render 'layouts/article_card', article: article %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="tx-center">

    <%= render 'layouts/ad' %>
    <%= render 'layouts/ad-mobile' %>

  </div>
  <div class="twelve cols">
    <div id="eroterest_partsv21" class="eroterest_partsv2"></div><script src="http://bpm.eroterest.net/v2/?w=%E3%83%8A%E3%83%B3%E3%83%91&e=%E7%84%A1%E4%BF%AE%E6%AD%A3&n=4&rn=4&spn=1&sprn=1&fc=&ts=1&tp=&tbg=&tsz=12&tr=&tc=333333&tmc=666666&tu=0&is=1&mts=0&ds=&dsz=&dr=&dc=&df=&ibg=&ibm=&ids=0&ib=&ibc=eeeeee&ir=2&sf=1"></script>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <%= render 'layouts/featured_videos' %>
</div>

<div class="row">
  <div class="left three cols">
    <%= render 'layouts/sidebar' %>
    <div class="twelve cols">
      <div class="row">
        <h6 class="sub-heading"><i class="icon ion-ios-paw"></i>&nbsp;素人動画</h6>
      </div>
      <div class="row tx-center">
        <style media="screen">
          ._erokawa_bp_card {
            width: 100% !important;
          }

          ._erokawa_bp_card img {
            width: 100% !important;
          }
        </style>
        <div id="_erokawa_blog_parts_7"></div>
        <script type="text/javascript" src="http://ero-kawa.com/blogparts/bpm.js.php?size=294&int=8&line=1&enc=0&num=4&gen=7&safe=1&wid=1230&clr=000000&bgc=FFFFFF"></script>
      </div>
    </div>
  </div>
  <div class="right nine cols">
    <div class="tx-center">

      <%= render 'layouts/ad' %>
      <%= render 'layouts/ad-mobile' %>

    </div>

    <div class="popular-videos">
      <div class="row">
        <h6 class="sub-heading"><i class="icon ion-ribbon-b"></i>&nbsp;人気動画</h6>
      </div>
      <% @popular_articles.each_slice(2) do |articles| %>
        <div class="row">
          <% articles.each do |article| %>
            <div class="six cols card">
              <%= render 'layouts/article_card', article: article %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="tx-center">

      <%= render 'layouts/ad' %>
      <%= render 'layouts/ad-mobile' %>

    </div>

    <div class="feature-videos">
      <div class="row">
        <h6 class="sub-heading"><i class="icon ion-flash"></i>&nbsp;新着動画</h6>
      </div>
      <% @latest_articles.each_slice(2) do |articles| %>
        <div class="row">
          <% articles.each do |article| %>
            <div class="six cols card">
              <%= render 'layouts/article_card', article: article %>
            </div>
          <% end %>
        </div>
      <% end %>
      <div class="row tx-center">
        <%= paginate @latest_articles %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_ad-mobile.html.erb
<!-- i-mobile for SmartPhone client script -->
<script type="text/javascript">
	imobile_tag_ver = "0.3";
	imobile_pid = "57982";
	imobile_asid = "1096383";
	imobile_type = "inline";
</script>
<script type="text/javascript" src="http://spad.i-mobile.co.jp/script/adssp.js?20110215"></script>

app/views/layouts/_article_card.html.erb
  <div class="head">
    <%= link_to article_path(id: article.id) do %>
    <i class="icon ion-ios-film"></i>&nbsp;<%= article.title %>
    <% end %>
    <% if request.path != favorites_articles_path %>
      <span data-video-id="<%= article.id %>" class="add-favorite-btn"><i class="icon ion-plus"></i>&nbsp;お気に入りに追加</span>
    <% end %>
  </div>
<div class="body summary">
  <%= link_to article_path(id: article.id) do %>
    <img src="<%= article.thumbnail %>" alt="<%= article.title %>" />
  <% end %>
  <div class="info video-summary">
    <p><%= article.description %></p>
    <div class="duration">
      <i class="icon ion-android-time"></i>&nbsp;<%= article.duration %>
    </div>
    <div class="host">
      <i class="icon ion-earth"></i>&nbsp;<%= article.host %>
    </div>
  </div>
  <% article.tag_list.each do |tag| %>
    <%= render 'layouts/tag', tag: tag %>
  <% end %>
</div>

app/views/layouts/_manage_side_bar.html.erb
<div class="sidebar twelve cols">
  <div class="card">
    <div class="head">
      <i class="icon ion-android-list"></i>&nbsp;メニュー
    </div>
    <div class="body card-menu">
      <ul>
        <%= link_to new_article_path do %>
          <li><i class="icon ion-plus"></i>&nbsp;記事投稿</li>
        <% end %>
        <%= link_to admin_path do %>
          <li><i class="icon ion-ios-speedometer"></i>&nbsp;記事管理</li>
        <% end %>
        <%= link_to tags_path do %>
          <li><i class="icon ion-ios-pricetags"></i>&nbsp;タグ管理</li>
        <% end %>
        <%= link_to "#", class: '', target: 'blank' do %>
          <li><i class="icon ion-ios-analytics"></i>&nbsp;Analytics</li>
        <% end %>
        <%= link_to "https://github.com/boobee/eropit#boards", class: '', target: 'blank' do %>
          <li><i class="icon ion-social-github"></i>&nbsp;Github Board</li>
        <% end %>
        <%= link_to "https://www.google.com/webmasters/tools/dashboard?hl=ja&authuser=1&siteUrl=http://nampa-picks.net/", class: '', target: 'blank' do %>
          <li><i class="icon ion-ios-cog-outline"></i>&nbsp;Search console</li>
        <% end %>
        <%= link_to fetch_path, class: '' do %>
          <li><i class="icon ion-document-text"></i>&nbsp;Fetch</li>
        <% end %>
      </ul>
    </div>
    <div class="foot">
      <%= link_to root_path, class: "full-x card-btn" do %>TOPに戻る<% end %>
    </div>
  </div>
</div>

app/views/layouts/_photo_article_card.html.erb
<%= link_to article_path(id: article.id) do %>
  <div class="image-head" style="background-image: url(<%= article.thumbnail %>);">
    <div class="corner-ribbon top-left sticky red shadow">人気</div>
    <div class="card-overlay"></div>
    <h5 class="title"><%= article.title %></h5>
    <span class="image-duration"><i class="icon ion-clock"></i>&nbsp;<%= article.duration %></span>
  </div>
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="sidebar twelve cols">
  <div class="card" style="margin-bottom: 8px;">
    <div class="head">
      <i class="icon ion-android-list"></i>&nbsp;サイトメニュー
    </div>
    <div class="body card-menu">
      <ul>
        <%= link_to root_path do %>
          <li><i class="icon ion-home"></i>&nbsp;トップ</li>
        <% end %>
        <%= link_to ranking_articles_path do %>
          <li><i class="icon ion-ribbon-b"></i>&nbsp;人気動画</li>
        <% end %>
        <span class="favorite-menu">
          <li><i class="icon ion-star"></i>&nbsp;お気に入り動画</li>
        </span>
      </ul>
      <div class="sidebar-search">
        <%= form_tag search_articles_path, method: :get do %>
          <span><i class="icon ion-search"></i>&nbsp;動画を検索</span>
          <%= text_field_tag :search, params[:search], placeholder: '動画を検索' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="card" style="margin-bottom: 8px;">
    <div class="head">
      <i class="icon ion-pricetags"></i>&nbsp;人気のタグ
    </div>
    <div class="body">
      <ul style="margin: 0">
        <% @sidebar_tags.each do |tag| %>
          <%= render 'layouts/tag', tag: tag %>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="card" style="margin-bottom: 8px;">
    <div class="head">
      <i class="icon ion-earth"></i>&nbsp;おすすめサイト
    </div>
    <div class="body card-menu">
      <ul>
        <a href="http://movie.eroterest.net/"><li><i class="icon ion-forward"></i>&nbsp;動画エロタレスト</li></a>
        <a href="http://ero-kawa.com"><li><i class="icon ion-forward"></i>&nbsp;えろかわちゃん！<a href="http://ero-kawa.com/rss.xml"><i class="icon ion-social-rss"></i></a></li></a>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_tag.html.erb
<%= link_to search_articles_path(search: tag.to_s), class: "tag" do %>
  <i class="icon ion-pricetag"></i>&nbsp;<%= tag %>
<% end %>

app/views/tags/edit.html.erb
<div class="row">
  <div class="left three cols">
    <%= render 'layouts/manage_side_bar' %>
  </div>
  <div class="right nine cols">
    <div class="card">
      <div class="head">
        Edit tag
      </div>
      <div class="body">
        <div class="tag-form">
          <%= form_tag(tag_path(@tag), { method: :put }) do %>
            <label>Name</label>
            <%= text_field :tag, :name %>
            <label>Mean</label>
            <%= text_field :tag, :mean %>
            <label>Prefix</label>
            <%= text_field :tag, :pre_words %>
            <label>Suffix</label>
            <%= text_field :tag, :suf_words %>
            <%= submit_tag 'Save', class: 'btn' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<style media="screen">
  .tag-form input {
    width: 100%;
  }
</style>

app/views/tags/index.html.erb
<div class="row">
  <div class="left three cols">
    <%= render 'layouts/manage_side_bar' %>
  </div>
  <div class="right nine cols">
    <div class="qw-box">
      <table class="full-x">
        <thead>
          <tr>
            <th>Name</th>
            <th>Mean</th>
            <th>Prefix</th>
            <th>Suffix</th>
          </tr>
        </thead>
        <tbody>
          <% @tags.each do |tag| %>
            <tr>
              <td><%= link_to tag.name, edit_tag_path(tag) %></td>
              <td><%= tag.mean %></td>
              <td><%= tag.pre_words %></td>
              <td><%= tag.suf_words %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="row tx-center">
      <%= paginate @tags %>
    </div>
  </div>
</div>